# Page copy.
EN=dict(lang='en',p='en',navlabel='Sections',
 nav=[('problem','Problem'),('how','How it works'),('why','Why MARS'),('cases','Mail & XDR'),('ai','AI'),('product','Product')],
 eyebrow='AI phishing analysis and incident response',
 h1='AI triage your SOC can check.',
 lead='MARS reads the suspicious mail your employees report and the incidents Microsoft Defender XDR raises. It gathers the evidence, asks an AI model for a judgement, and publishes only the answers that evidence supports.',
 cta=('See how it works','Why MARS'),
 facts=['Self-hosted','Bring your own model','Version 1.5','AGPL-3.0'],
 mocklabel='Illustration of an AI verdict card',
 m_title='AI verdict',m_verdict='Phishing',m_subj='Subject: Action required: your mailbox is almost full',
 claims=[('The sending domain does not belong to the brand shown','Evidence · header check'),('The link opens a copy of a sign-in page','Evidence · sandbox'),('The domain was registered this week','Evidence · domain age')],
 m_foot='Proposed: block the sender domain',m_wait='Awaiting approval',
 m_held='Needs review',m_heldwhy='Another case: the AI cited evidence that was never collected.',
 m_note='Illustration, not a screenshot',
 problem_h='AI triage is easy to build and hard to trust.',
 problem_p='Security teams want a model to take the first pass. Four things get in the way.',
 problem=[('Too much to read','Reported mail and XDR incidents arrive faster than a small team can open them.'),('Confident is not correct','A model can sound certain and be wrong. A wrong "safe" is expensive.'),('The input is hostile','The mail was written by an attacker, sometimes with text aimed at the AI.'),('The data is sensitive','Reported mail holds internal correspondence. It cannot go to just any cloud service.')],
 how_h='Evidence in, checked answer out.',
 how_p='Every case follows the same path, and the last step decides whether an analyst sees a verdict at all.',
 rail=[('A case arrives','Reported mail, an uploaded message file, an XDR incident'),('Evidence is gathered','Sender, links, attachments, threat intelligence'),('The AI judges','A verdict, its reasons, the next steps'),('The answer is checked','Each claim must rest on evidence MARS collected')],
 **{'pass':('Passes: published','The analyst sees the verdict, the reasoning and the suggested steps.'),'hold':('Fails: needs review','No verdict is shown. The case goes to an analyst as it is.')},
 why_e='Why MARS',why_h='The model is one step in a pipeline MARS controls.',
 why_p='Checks sit on both sides of it.',
 why=[('It can decline to answer','When evidence is thin, the case stays undecided and goes to a person.'),('Claims are checked against evidence','If the AI cites something MARS never collected, the conclusion does not stand.'),('Unfinished never looks final','A case still in progress shows its progress and nothing else.'),('People approve every action','MARS proposes remediation, never runs it alone, and verifies the outcome afterwards.'),('Attacker text stays data','Mail bodies, file names and links reach the model as material to examine, never as instructions.'),('You choose where the AI runs','A hosted model, a company gateway or a local model. The host decides which endpoints are allowed.')],
 cases_h='Two kinds of case, one standard.',
 cases_p='Mail and XDR incidents are prepared differently and judged by the same rules.',
 mail_h='Reported mail',mail_p='Employees forward suspicious mail to a reporting mailbox. MARS picks it up automatically.',
 mail=[('Is the sender who they claim to be?','Authentication results, the sending domain, brand impersonation, lookalike domains.'),('Where do the links lead?','Every link is scored and can be opened in an isolated browser.'),('What is inside the attachments?','Documents, archives and PDFs are examined without being run.'),('Has this been seen before?','Threat intelligence, past analyses, first-time senders.'),('The AI weighs the evidence','A verdict, the reasons for it, the recommended steps.')],
 verdict='Verdict ',mail_pills=[('bad','Phishing'),('warn','Suspicious'),('ok','Legitimate')],
 xdr_h='XDR incidents',xdr_p='MARS syncs incidents from Microsoft Defender XDR and prepares each one before an analyst opens it.',
 xdr=[('The incident itself','Alerts and the devices, accounts and files involved.'),('Links to mail','Related mail MARS has analysed, and who else received it.'),('Endpoint and account context','Device activity, sign-in history, known vulnerabilities.'),('What the organisation knows','What is normal in this environment and what is not.'),('The AI weighs the evidence','A classification, its reasons, the evidence still missing.')],
 klass='Classification ',xdr_pills=[('bad','True positive'),('neutral','Informational'),('ok','False positive'),('warn','Needs review')],
 gets_h='What lands on the analyst\'s desk',
 gets=['A verdict with its reasons and evidence','Recommended investigation and response steps','Indicators to pursue: links, domains, file hashes','Ready-to-run hunting queries for XDR incidents','A draft reply to the person who reported the mail','Response-time (SLA) tracking for incidents'],
 ai_h='Built around the model, not on faith in it.',
 ai_p='The model reads and reasons. MARS decides what it sees and what becomes of its answer.',
 ai=[('A fixed answer format','The model answers within defined fields and options. Anything else is discarded.'),('A model for each job','Mail, XDR incidents, sandbox results and the analyst assistant can each use a different one.'),('Budgets','Every call is counted against a daily budget before it is sent.'),('Tested before any change','Before a model or its instructions change, known cases are replayed. A drop in quality blocks the change.'),('Two languages','Answers are produced in English and translated into Traditional Chinese in the background.'),('An audit trail','Who did what, and when, is written to a signed log.')],
 product_h='A working console, not a demo.',
 product_p='Eleven pages cover the analyst\'s day, in Traditional Chinese and English, light and dark.',
 pages=[('Mail report overview','Report volume, results and mail waiting for a person.'),('Mail analysis','Upload a message file and analyse it now.'),('Mail history','Search and filter completed analyses.'),('Mailbox monitoring','Bring in new mail from the reporting mailbox.'),('AI processing','Cases being analysed, with their progress.'),('XDR incident queue','Review and triage incidents.'),('Advanced analysis','Exposure, hotspots and risk across incidents.'),('Remediation','Review proposed actions, run them, confirm the result.'),('IOC database','Manage indicators and sync outside intelligence.'),('Sandbox','Open suspicious links in isolation.'),('AI quality','Manage validation cases and track judgement quality.')],
 integ=[('MICROSOFT',['Microsoft 365 mail','Defender XDR','Defender for Endpoint','Entra ID']),('THREAT INTELLIGENCE',['VirusTotal','AbuseIPDB','URLhaus','ThreatFox','MalwareBazaar','PhishTank','STIX/TAXII','CISA KEV']),('AI MODELS',['Anthropic','OpenAI','Gemini','Local models','Company gateways']),('NOTIFICATIONS',['Email','Teams','Slack'])],
 deploy_h='Your host, your data.',
 deploy_p='MARS is built for teams that cannot hand their mail to someone else.',
 deploy=[('Self-hosted','Analysis records and audit logs stay on the organisation\'s own host.'),('Controlled AI endpoints','The host administrator sets which AI endpoints may be reached. The console cannot widen the list.'),('Four roles','Read-only, analyst, SOC analyst, administrator. Secrets never appear in the console.'),('Offline updates','A host with no internet access can still be updated, with verification, a dry run and a backup first.'),('Little to operate','One instance with an embedded database, sized for one security team.'),('Open source','Released under the GNU AGPL, version 3 or later.')],
 footer='Version 1.5 · October 2026')
