# Page copy, English and Traditional Chinese.
EN=dict(lang='en',p='en',navlabel='Sections',
 nav=[('problem','Problem'),('how','How it works'),('why','Why MARS'),('cases','Mail & XDR'),('ai','AI'),('product','Product')],
 eyebrow='AI phishing analysis and incident response',
 h1='AI triage your SOC can check.',
 lead='MARS reads the suspicious mail your employees report and the incidents Microsoft Defender XDR raises. It gathers the evidence, asks an AI model for a judgement, and publishes only the answers that evidence supports.',
 cta=('See how it works','Why MARS'),
 facts=['Self-hosted','Bring your own model','Version 1.5','MIT licence'],
 mocklabel='Illustration of an AI verdict card',
 m_title='AI verdict',m_verdict='Phishing',m_subj='Subject: Action required: your mailbox is almost full',
 claims=[('The sending domain does not belong to the brand shown','Evidence · header check'),('The link opens a copy of a sign-in page','Evidence · sandbox'),('The domain was registered this week','Evidence · domain age')],
 m_foot='Proposed: block the sender domain',m_wait='Awaiting approval',
 m_held='Needs review',m_heldwhy='Another case: the AI cited evidence that was never collected.',
 m_note='Illustration, not a screenshot',
 problem_h='AI triage is easy to build and hard to trust.',
 problem_p='Security teams want a model to take the first pass. Four things get in the way.',
 problem=[('Too much to read','Reported mail and XDR incidents arrive faster than a small team can open them.'),('Confident is not correct','A model can sound certain and be wrong. A wrong "safe" is expensive.'),('The input is hostile','The mail was written by an attacker, sometimes with text aimed at the AI.'),('The data is sensitive','Reported mail holds internal correspondence. It cannot go to just any cloud service.')],
 how_h='Evidence in, checked answer out.',
 how_p='Every case follows the same path, and the last step decides whether an analyst sees a verdict at all.',
 rail=[('A case arrives','Reported mail, an uploaded message file, an XDR incident'),('Evidence is gathered','Sender, links, attachments, threat intelligence'),('The AI judges','A verdict, its reasons, the next steps'),('The answer is checked','Each claim must rest on evidence MARS collected')],
 **{'pass':('Passes: published','The analyst sees the verdict, the reasoning and the suggested steps.'),'hold':('Fails: needs review','No verdict is shown. The case goes to an analyst as it is.')},
 why_e='Why MARS',why_h='The model is one step in a pipeline MARS controls.',
 why_p='Checks sit on both sides of it.',
 why=[('It can decline to answer','When evidence is thin, the case stays undecided and goes to a person.'),('Claims are checked against evidence','If the AI cites something MARS never collected, the conclusion does not stand.'),('Unfinished never looks final','A case still in progress shows its progress and nothing else.'),('People approve every action','MARS proposes remediation, never runs it alone, and verifies the outcome afterwards.'),('Attacker text stays data','Mail bodies, file names and links reach the model as material to examine, never as instructions.'),('You choose where the AI runs','A hosted model, a company gateway or a local model. The host decides which endpoints are allowed.')],
 cases_h='Two kinds of case, one standard.',
 cases_p='Mail and XDR incidents are prepared differently and judged by the same rules.',
 mail_h='Reported mail',mail_p='Employees forward suspicious mail to a reporting mailbox. MARS picks it up automatically.',
 mail=[('Is the sender who they claim to be?','Authentication results, the sending domain, brand impersonation, lookalike domains.'),('Where do the links lead?','Every link is scored and can be opened in an isolated browser.'),('What is inside the attachments?','Documents, archives and PDFs are examined without being run.'),('Has this been seen before?','Threat intelligence, past analyses, first-time senders.'),('The AI weighs the evidence','A verdict, the reasons for it, the recommended steps.')],
 verdict='Verdict ',mail_pills=[('bad','Phishing'),('warn','Suspicious'),('ok','Legitimate')],
 xdr_h='XDR incidents',xdr_p='MARS syncs incidents from Microsoft Defender XDR and prepares each one before an analyst opens it.',
 xdr=[('The incident itself','Alerts and the devices, accounts and files involved.'),('Links to mail','Related mail MARS has analysed, and who else received it.'),('Endpoint and account context','Device activity, sign-in history, known vulnerabilities.'),('What the organisation knows','What is normal in this environment and what is not.'),('The AI weighs the evidence','A classification, its reasons, the evidence still missing.')],
 klass='Classification ',xdr_pills=[('bad','True positive'),('neutral','Informational'),('ok','False positive'),('warn','Needs review')],
 gets_h='What lands on the analyst\'s desk',
 gets=['A verdict with its reasons and evidence','Recommended investigation and response steps','Indicators to pursue: links, domains, file hashes','Ready-to-run hunting queries for XDR incidents','A draft reply to the person who reported the mail','Response-time (SLA) tracking for incidents'],
 ai_h='Built around the model, not on faith in it.',
 ai_p='The model reads and reasons. MARS decides what it sees and what becomes of its answer.',
 ai=[('A fixed answer format','The model answers within defined fields and options. Anything else is discarded.'),('A model for each job','Mail, XDR incidents, sandbox results and the analyst assistant can each use a different one.'),('Budgets','Every call is counted against a daily budget before it is sent.'),('Tested before any change','Before a model or its instructions change, known cases are replayed. A drop in quality blocks the change.'),('Two languages','Answers are produced in English and translated into Traditional Chinese in the background.'),('An audit trail','Who did what, and when, is written to a signed log.')],
 product_h='A working console, not a demo.',
 product_p='Eleven pages cover the analyst\'s day, in Traditional Chinese and English, light and dark.',
 pages=[('Mail report overview','Report volume, results and mail waiting for a person.'),('Mail analysis','Upload a message file and analyse it now.'),('Mail history','Search and filter completed analyses.'),('Mailbox monitoring','Bring in new mail from the reporting mailbox.'),('AI processing','Cases being analysed, with their progress.'),('XDR incident queue','Review and triage incidents.'),('Advanced analysis','Exposure, hotspots and risk across incidents.'),('Remediation','Review proposed actions, run them, confirm the result.'),('IOC database','Manage indicators and sync outside intelligence.'),('Sandbox','Open suspicious links in isolation.'),('AI quality','Manage validation cases and track judgement quality.')],
 integ=[('MICROSOFT',['Microsoft 365 mail','Defender XDR','Defender for Endpoint','Entra ID']),('THREAT INTELLIGENCE',['VirusTotal','AbuseIPDB','URLhaus','ThreatFox','MalwareBazaar','PhishTank','STIX/TAXII','CISA KEV']),('AI MODELS',['Anthropic','OpenAI','Gemini','Local models','Company gateways']),('NOTIFICATIONS',['Email','Teams','Slack'])],
 deploy_h='Your host, your data.',
 deploy_p='MARS is built for teams that cannot hand their mail to someone else.',
 deploy=[('Self-hosted','Analysis records and audit logs stay on the organisation\'s own host.'),('Controlled AI endpoints','The host administrator sets which AI endpoints may be reached. The console cannot widen the list.'),('Four roles','Read-only, analyst, SOC analyst, administrator. Secrets never appear in the console.'),('Offline updates','A host with no internet access can still be updated, with verification, a dry run and a backup first.'),('Little to operate','One instance with an embedded database, sized for one security team.'),('Open source','Released under the MIT licence.')],
 footer='Version 1.5 · October 2026')

ZH=dict(lang='zh-Hant',p='zh',navlabel='章節',
 nav=[('problem','問題'),('how','怎麼運作'),('why','為什麼選 MARS'),('cases','郵件與 XDR'),('ai','AI'),('product','產品')],
 eyebrow='AI 釣魚郵件分析與事件回應',
 h1='資安團隊查得了證的 AI 分流。',
 lead='MARS 讀取同仁回報的可疑郵件和 Microsoft Defender XDR 的事件，收集證據、請 AI 模型判斷，只發佈有證據支持的答案。',
 cta=('看它怎麼運作','為什麼選 MARS'),
 facts=['自架','自選模型','1.5 版','MIT 授權'],
 mocklabel='AI 判定卡示意',
 m_title='AI 判定',m_verdict='釣魚',m_subj='主旨：請立即處理：您的信箱容量即將用盡',
 claims=[('寄件網域不屬於信中顯示的品牌','證據 · 標頭檢查'),('連結打開的是仿冒的登入頁','證據 · 沙箱'),('網域在本週才註冊','證據 · 網域年齡')],
 m_foot='建議：封鎖寄件網域',m_wait='等待核准',
 m_held='需要複核',m_heldwhy='另一件案子：AI 引用了沒被收集到的證據。',
 m_note='示意畫面，不是實際截圖',
 problem_h='AI 分流做起來容易，要讓人信任很難。',
 problem_p='資安團隊希望讓模型先看第一輪，但有四件事擋在前面。',
 problem=[('量太大','回報郵件和 XDR 事件進來的速度，超過小團隊打得開的速度。'),('有把握不等於正確','模型可以講得很肯定卻是錯的。一次錯誤的「安全」代價很高。'),('輸入帶有敵意','郵件是攻擊者寫的，有時還夾帶針對 AI 的文字。'),('資料很敏感','回報郵件裡有內部往來，不能送到任意的雲端服務。')],
 how_h='證據進去，檢查過的答案出來。',
 how_p='每件案子走同一條路；最後一步決定分析師會不會看到判定。',
 rail=[('收到案件','回報的郵件、上傳的郵件檔、XDR 事件'),('收集證據','寄件者、連結、附件、威脅情資'),('AI 判斷','判定、理由、後續步驟'),('檢查答案','每一項說法都要有 MARS 收集到的證據')],
 **{'pass':('通過：發佈結果','分析師看到判定、理由和建議步驟。'),'hold':('沒通過：需要複核','不顯示判定，原樣交給分析師。')},
 why_e='為什麼選 MARS',why_h='模型只是 MARS 掌控的流程裡的一步。',
 why_p='它的前後都有檢查。',
 why=[('它可以不回答','證據太少時，案件保持未判定，交給人處理。'),('說法要對得上證據','AI 引用了 MARS 沒收集到的東西，結論就不成立。'),('沒完成的不像結論','還在分析的案件只顯示進度。'),('每個動作都由人核准','MARS 提出處置建議，不會自己執行，事後還會確認結果。'),('攻擊者的文字只是資料','郵件內文、檔名和連結交給模型時是待檢查的材料，不是指示。'),('AI 在哪裡跑由你決定','雲端模型、公司閘道或本機模型都可以，可連線的位址由主機決定。')],
 cases_h='兩種案件，同一套標準。',
 cases_p='郵件和 XDR 事件的準備方式不同，判斷的規則相同。',
 mail_h='回報郵件',mail_p='同仁把可疑郵件轉寄到回報信箱，MARS 自動收進來。',
 mail=[('寄件者是不是本人？','驗證結果、寄件網域、品牌冒用、相似網域。'),('連結通往哪裡？','每個連結都會評分，必要時在隔離的瀏覽器裡打開。'),('附件藏了什麼？','不執行檔案，直接檢查文件、壓縮檔和 PDF。'),('以前見過嗎？','威脅情資、過去的分析、首次來信的寄件者。'),('AI 綜合證據','判定、理由和建議步驟。')],
 verdict='判定 ',mail_pills=[('bad','釣魚'),('warn','需要留意'),('ok','正常')],
 xdr_h='XDR 事件',xdr_p='MARS 同步 Microsoft Defender XDR 的事件，在分析師打開之前先整理好。',
 xdr=[('事件本身','告警，以及涉及的裝置、帳號和檔案。'),('和郵件的關聯','MARS 分析過的相關郵件，以及還有誰收到。'),('端點與帳號的脈絡','裝置活動、登入紀錄、已知弱點。'),('組織自己的知識','這個環境裡什麼算正常，什麼不算。'),('AI 綜合證據','分類、理由，以及還缺的證據。')],
 klass='分類 ',xdr_pills=[('bad','確認為威脅'),('neutral','資訊性'),('ok','誤判'),('warn','需要複核')],
 gets_h='分析師手上會有什麼',
 gets=['判定，以及背後的理由和證據','建議的調查與處置步驟','可追查的指標：連結、網域、檔案雜湊','XDR 事件可直接執行的搜捕查詢','給回報者的回覆草稿','事件回應時限（SLA）的追蹤'],
 ai_h='圍著模型設計，而不是相信模型。',
 ai_p='閱讀和推理交給模型；模型看到什麼、答案怎麼處理，由 MARS 決定。',
 ai=[('固定的回覆格式','模型只能在規定的欄位和選項裡作答，其餘一律不採用。'),('不同工作用不同模型','郵件、XDR 事件、沙箱結果和分析師助理可以各自選用。'),('預算','每次呼叫送出前都先計入每日預算。'),('變更前先測試','更換模型或調整指示之前，先重跑已知答案的案例；品質退步就不上線。'),('雙語','答案以英文產生，在背景翻成繁體中文。'),('稽核軌跡','誰在什麼時候做了什麼，都寫進有簽章的日誌。')],
 product_h='已經能用的主控台，不是展示品。',
 product_p='十一個頁面涵蓋分析師的日常工作，有繁體中文和英文、淺色和深色。',
 pages=[('郵件回報總覽','回報量、分析結果和待人處理的郵件。'),('郵件分析','上傳郵件檔，立即分析。'),('郵件分析紀錄','搜尋和篩選已完成的分析。'),('回報信箱監控','自動收進回報信箱的新郵件。'),('AI 分析中','正在分析的案件和進度。'),('XDR 事件佇列','檢視事件並分流。'),('進階分析','跨事件的曝險、熱點和風險。'),('處置驗證','審核處置建議、執行並確認結果。'),('IOC 資料庫','管理威脅指標，同步外部情資。'),('沙箱','在隔離環境裡打開可疑連結。'),('AI 品質治理','管理驗證案例，追蹤判斷品質。')],
 integ=[('MICROSOFT',['Microsoft 365 郵件','Defender XDR','Defender for Endpoint','Entra ID']),('威脅情資',['VirusTotal','AbuseIPDB','URLhaus','ThreatFox','MalwareBazaar','PhishTank','STIX／TAXII','CISA KEV']),('AI 模型',['Anthropic','OpenAI','Gemini','本機模型','公司閘道']),('通知',['Email','Teams','Slack'])],
 deploy_h='你的主機，你的資料。',
 deploy_p='MARS 是為了不能把郵件交給別人的團隊設計的。',
 deploy=[('自架','分析紀錄和稽核日誌都留在組織自己的主機上。'),('受控的 AI 連線','可連線的 AI 服務位址由主機管理者設定，主控台無法放寬。'),('四種角色','唯讀、分析師、SOC 分析師、管理員。密鑰不會出現在主控台。'),('離線更新','沒有對外網路的主機也能更新，更新前先驗證、試套並備份。'),('維運負擔小','單一實例加內嵌資料庫，適合一個資安團隊。'),('開放原始碼','以 MIT 授權釋出。')],
 footer='1.5 版 · 2026 年 10 月')

